### PR TITLE
Feature gtune log

### PR DESCRIPTION
**Pull request by ledvinap**
_This PR is mainly for reference and discussion_

Here is implementation of @MJ666 GTune events. No need to merge before GTune.

@thenickdude : should I create separate PR with JSON quotes? Some libraries (http://sourceforge.net/projects/iso2mesh/files/jsonlab/) don't work without it ...

### CODE REVIEW

**Comment by thenickdude** [comment]
Hi @ledvinap! Including those changes to add quotes in this PR this fine, thanks. Can you link a log with these new events in it for testing? Thanks!

**Comment by ledvinap** [comment]
@MJ666 posted some logs in GTune PR. I did not test G-Tune yet ...

**Comment by thenickdude** [comment]
Thanks, this has now been released as part of v0.3.4!

**Comment by hydra** [comment]
Nice

**Pull request merged**
